[env:nano33ble]
platform  = nordicnrf52
board     = nano33ble
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

lib_deps =
    arduino-libraries/Arduino_LSM9DS1
    arduino-libraries/ArduinoBLE
